before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/fcqs-cli/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: fcqs-cli
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  use: github-native
release:
  prerelease: auto
